# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lounge Mix
tagline:             'the GIT Blabling System'
description:         'Cicero Younger, the GIT Blabling System'
url:                 http://loungemix.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Cicero Younger
  url:               https://ciceroyounger.github.io
  email:             ciceroyounger@gmail.com

# Custom vars
version:             0.0.1

github:
  repo:               loungemix/loungemix.github.io
  branch:             master
